name: Close stale issues

on:
  workflow_call:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/stale@v10
        with:
          stale-issue-message: >-
            This issue has been marked as stale because it has not had recent activity.
            The bot will close the issue if no further action occurs.
          stale-pr-message: >-
            This PR has been marked as stale because it has not had recent activity.
            The bot will close the PR if no further action occurs.
          exempt-issue-labels: pinned
          exempt-pr-labels: pinned
          stale-issue-label: stale
          stale-pr-label: stale
          days-before-close: 30
          days-before-stale: 90
